import React from 'react'

const TermsConditions = () => {
  return (
    <>
    <section className='section-spacing bg-light-color'>
        <div className="width-container">
            <div className="row">
                <div className="col-lg-10 mx-auto pt-5 pb-5">
                  <div className="main-title text-center">
                        <h2>Terms of <span>Service</span></h2>
                  </div>
                </div>
            </div>
        </div>
    </section>
    
  <section className="content-page section-spacing">
        <div className="width-container">
            <div className="row">
             <div className="col-lg-12 mx-auto paragraph-policy">
               <h6 className='pt-3 pb-3'>Website and Service Terms and Conditions - General</h6>  
               <p>The Testerika website ("Website") and related services (together with the Website, the "Service") are operated by Testerika Edu aSolutions Pvt. Ltd. ("Testerika", "us" or "we"). Access and use of the Service is subject to the following Terms and Conditions of Service ("Terms and Conditions"). By accessing or using any part of the Service, you represent that you have read, understood, and agree to be bound by these Terms and Conditions including any future modifications. Testerika may amend, update or change these Terms and Conditions. If we do this, we will post a notice that we have made changes to these Terms and Conditions on the Website for at least 7 days after the changes are posted and will indicate at the bottom of the Terms and Conditions the date these terms were last revised. Any revisions to these Terms and Conditions will become effective the earlier of (i) the end of such 7-day period or (ii) the first time you access or use the Service after such changes. If you do not agree to abide by these Terms and Conditions, you are not authorized to use, access or participate in the Service.</p> 
               <h6 className='pt-3 pb-3'>Description of Website and Service</h6>  
               <p>The Service allows users to prepare for any examination online by offering (a) Test Series e-module (b) Test Series e-module printed version and (c) evaluation services as opted/selected by Users. Users interested in learning or practicing are presented with different types of educational activities. Testerika may, in its sole discretion and at any time, update, change, suspend, make improvements to or discontinue any aspect of the Service, temporarily or permanently.</p>
               <h6 className='pt-3 pb-3'>Registration</h6>
               <p>In connection with registering for and using the Service, you agree (i) to provide accurate, current and complete information about you and/or your organization as requested by Testerika; (ii) to maintain the confidentiality of your password and other information related to the security of your account; (iii) to maintain and promptly update any registration information you provide to Testerika while registering or during your usage of Testerika's services, to keep such information accurate, current and complete; (iv) to be fully responsible for all use of your account and for any actions that take place through your account; (v) By signing up on Testerika you deemed to have given your consent to be contacted by us via phone calls and/or SMS notifications and offer you our services, imparting product knowledge, offer promotional, offers running on website/app, offers offered by the associated third parties and also order/shipment/delivery related updates, irrespective of the fact if also you have registered yourself under DND or DNC or NCPR service, you still authorize Testerika to give you a call for the above mentioned purposes. (vi) You are required to provide your examination registration information for the purpose of our internal estimation of successful candidates. If you do not provide the information, your partial or full access to the website content and/or other Testerika services may be blocked. No refund will be provided in such scenario. We assure you that we will not use this information for any other purpose or share this information with any third party.</p>
               <h6 className='pt-3 pb-3'>Subscriptions</h6>
               <p className='pb-3'>You may choose to purchase a monthly or annual subscription and download the Application through a third party platform. Alternatively, you may subscribe to our Services through our website and then download the related Application through a third party platform.</p>
               <p className='pb-3'>When you purchase a subscription, payment may be processed by third parties who act on our behalf or directly by the third party platform (e.g. Apple or Google). Rates for services are listed in the Application and in the applicable app store. Testerika reserves the right to modify its rates at any time and/or to offer special promotions. All payments are non-refundable. Subscription payments will auto-renew unless cancelled in accordance with the Terms of Service. If you purchased the Application through a third party platform and have a billing dispute, you must contact the respective third party platform to seek a remedy. If you purchased a subscription to our Services through our Online Services, please Contact Us.</p>
               <p className='pb-3'>Free Trial. We may provide a free trial period during which you can use all features of the Services for a limited period of time. You acknowledge and agree that your free-trial subscription will automatically renew as a paid subscription unless you cancel before the end of the trial period in accordance with the Cancellation section of the Terms of Service.</p>
               <p>Automatic Renewal. Paid subscriptions to our Services are auto-renewing. You will be charged the stated subscription amount for the subscription period upon completion of your registration and submission of your payment information or, if applicable, at the end of your free trial period if you have not canceled at least 24 hours in advance of the expiration of the trial period. You hereby agree to and authorize automatic (recurring) billing, and you agree to pay the charges made to your account in connection therewith. You will be billed at the then-current applicable subscription price plus any applicable taxes. Payments for renewal subscriptions are processed using the same billing cycle as your current subscription. Subscription fees may change at any time, to the fullest extent permitted under applicable law. Your subscription, and monthly billing of your account, will continue indefinitely until cancelled by you in accordance with the Cancellation section of the Terms of Service.</p>
               <h6 className='pt-3 pb-3'>Your Representations and Warranties</h6>
               <p>You represent and warrant to Testerika that your access and use of the Service will be in accordance with these Terms and Conditions and with all applicable laws, rules and regulations of Constitution of India and any other relevant jurisdiction, including those regarding online conduct or acceptable content, and those regarding the transmission of data or information exported from India and/or the jurisdiction in which you reside. You further represent and warrant that you have created or own any material you submit to Testerika and that you have the right to grant us a license to use that material.</p>
               <h6 className='pt-3 pb-3'>Inappropriate Use</h6>
               <p>You will not upload, display or otherwise provide on or through the Service any content that: (i) is libelous, defamatory, abusive, threatening, harassing, hateful, offensive or otherwise violates any law or infringes upon the right of any third party (including copyright, trademark, privacy, publicity or other personal or proprietary rights); or (ii) in Testerika's sole judgment, is objectionable or which restricts or inhibits any other person from using the Service or which may expose Testerika or its users to any harm or liability of any kind.</p>
               <h6 className='pt-3 pb-3'>Indemnification of Testerika</h6>
               <p>You agree to defend, indemnify and hold harmless Testerika and its directors, officers, employees, contractors, agents, suppliers, licensors, successors and assigns, from and against any and all losses, claims, causes of action, obligations, liabilities and damages whatsoever, including attorneys' fees, arising out of or relating to your access or use of the Service, any false representation made to us (as part of these Terms and Conditions or otherwise), your breach of any of these Terms and Conditions,or any claim that any service we provide to you is inaccurate, inappropriate or defective in any way whatsoever.</p>
               <h6 className='pt-3 pb-3'>No Representations or Warranties</h6>
               <p>The service, including all images, audio files and other content therein, and any other information, property and rights granted or provided to you by Testerika are provided to you on an "as is" basis. Testerika and its suppliers make no representations or warranties of any kind with respect to the service, either express or implied, and all such representations and warranties, including warranties of merchantability, fitness for a particular purpose or non-infringement, are expressly disclaimed. Without limiting the generality of the foregoing, Testerika does not make any representation or warranty of any kind relating to accuracy, service availability, completeness, informational content, error-free operation, results to be obtained from use, or non-infringement. Access and use of the service may be unavailable during periods of peak demand, system upgrades, malfunctions or scheduled or unscheduled maintenance or for other reasons. Some jurisdictions do not allow the exclusion of implied warranties, so the above exclusion may not apply to you.</p>
               <h6 className='pt-3 pb-3'>Limitation on types of Damages/Limitation of Liability</h6>
               <p>In no event will Testerika be liable to you or any third party claiming through you (whether based in contract, tort, strict liability or other theory) for indirect, incidental, special, consequential or exemplary damages arising out of or relating to the access or use of, or the inability to access or use, the service or any portion thereof, including but not limited to the loss of use of the service, inaccurate results, loss of profits, business interruption, or damages stemming from loss or corruption of data or data being rendered inaccurate, the cost of recovering any data, the cost of substitute services or claims by third parties for any damage to computers, software, modems, telephones or other property, even if Testerika has been advised of the possibility of such damages. Testerika's liability to you or any third party claiming through you for any cause whatsoever, and regardless of the form of the action, is limited to the amount paid, if any, by you to Testerika for the service in the 12 months prior to the initial action giving rise to liability. This is an aggregate limit. The existence of more than one claim hereunder will not increase this limit.</p>
               <h6 className='pt-3 pb-3'>Termination</h6>
               <p>Testerika may terminate your access and use of the Service immediately at any time, for any reason, and at such time you will have no further right to use the Service. You may terminate your Testerika account at any time by following the instructions available through the Service. The provisions of these Terms and Conditions relating to the protection and enforcement of Testerika's proprietary rights, your representations and warranties, disclaimer of representations and warranties, release and indemnities, limitations of liability and types of damages, ownership of data and information, governing law and venue, and miscellaneous provisions shall survive any such termination.</p>
               <h6 className='pt-3 pb-3'>Proprietary Rights in Service Content and Activity Data</h6>
               <p>All content available through the Service, including designs, text, graphics, images, information, software, audio, e-books,and other files, and their selection and arrangement (the "Service Content") along with printed version of e-books, are the proprietary property of Testerika or its licensors. No Service Content along with printed version of e-books may be modified, copied, distributed, framed, reproduced, republished, downloaded, scraped, displayed, posted, transmitted, or sold in any form or by any means, in whole or in part, other than as expressly permitted in these Terms and Conditions. You may not use any data mining, robots, scraping or similar data gathering or extraction methods to obtain Service Content. As between you and Testerika, all data and information generated from your access and use of the educational activities made available on or through the Service, including translated content generated by you (collectively, the "Activity Data"), shall be exclusively owned by Testerika, and you shall not have any right to use such Activity Data except as expressly authorized by these Terms and Conditions. Activity Data will not include material you submit for translation or any resulting translation. By using the Service, you hereby assign to Testerika any and all rights, title and interest, including any intellectual property rights or proprietary rights, in the Activity Data. All rights of Testerika or its licensors that are not expressly granted in these Terms and Conditions are reserved to Testerika and its licensors.</p>
               <h6 className='pt-3 pb-3'>Trademarks</h6>
               <p>"Testerika" and all other trademarks, service marks, graphics and logos used in connection with the Service are trademarks or service marks of Testerika or their respective owners. Access and use of the Service does not grant or provide you with the right or license to reproduce or otherwise use the Testerika name or any Testerika or third-party trademarks, service marks, graphics or logos.</p>
               <h6 className='pt-3 pb-3'>Privacy</h6>
               <p>Use of the Service is also governed by our Privacy Policy, a copy of which is located at <a className='theme-color' href="https://www.testerika.com/privacy-policy/">Testerika.com/privacy-policy.</a> By using the Service, you consent to the terms of the Privacy Policy.</p>
               <h6 className='pt-3 pb-3'>Cancellation Policy</h6>
               <ul className='m-0 p-0 mb-3 ms-4 pt-3'>
                 <li>Cancellations will be considered only if the cancellation request is made within 24 hours of placing the order. However, the cancellation request will not be entertained if the orders have already been completed or if we have initiated the process of shipping either by ourselves or through the vendors/merchants/representatives whom we may appoint from time to time.</li>       
                 <li>No cancellations are allowed for products on which Testerika marketing team has given special offers for various purposes including but not limited to special occasions like New Year, festivals, specific examination etc. These are limited validity offers and therefore cancellations are not possible.</li>       
                 <li>In case you feel that the product received is not as shown on the site and/or as per your expectations, you must bring it to the notice of our customer service within 24 hours of receiving the product. The customer service team, after looking into your complaint, will make an appropriate decision.</li>       
                </ul>
                <h6 className='pt-3 pb-3'>Refund Policy</h6>
                 <ul className='m-0 p-0 mb-3 ms-4 pt-3'>
                  <li>The refund is applicable for our products/services only until it’s dispatched or the login details for online access to test material etc. are disclosed/dispatched to you.</li>       
                  <li>Please include your order number (sent to you via email after your order) and do tell us why you’re requesting a refund. We take customer feedback very seriously and use it to constantly improve our products and quality of service.</li>       
                  <li>All refunds, if eligible, will be processed within 14 (Fourteen) business days of receiving cancellation request and mode of refund would be same through which the original transaction was done.</li>       
                </ul>
                <h6 className='fw-bold theme-color mb-3'>Notice for Claims of Copyright Violations and Agent for Notice</h6>
                <p className='fw-bold'>If you are a copyright owner and have a good faith belief that any material available through the service infringes upon your copyrights, you may submit a copyright infringement notification to Testerika pursuant to the Digital Millennium Copyright Act by providing us with the following information in writing:</p>
                <ul className='m-0 p-0 mb-3 ms-4 pt-3'>
                  <li>an electronic or physical signature of the copyright owner or the person authorized to act on behalf of the owner of the copyright interest;
                  </li>       
                  <li>a description of the copyrighted work that you claim has been infringed;
                  </li>       
                  <li>a description of where the material that you claim is infringing is located on the Service, with enough detail that we may find it on the Service;
                  </li> 
                  <li>your address, telephone number, and email address;
                  </li>       
                  <li>a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and
                  </li>       
                  <li>a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or are authorized to act on the copyright owner's behalf.
                  </li>       
                </ul>
                <p className='pt-3'>Please consult your legal counsel for further details or see Section 51 of The Copyright Act, 1957. Testerika's Agent for Notice of claims of copyright infringement can be reached as follows: By email: <span className='theme-color'>thetesterika@gmail.com</span> </p>
                <h6 className='pt-3 pb-3'>Governing Law and Arbitration</h6>
                <p>These Terms and Conditions, its subject matter and Testerika's and your respective rights under these Terms and Conditions shall be governed by the laws of India and you agree that the courts of Mumbai will have exclusive jurisdiction over any dispute (contractual or non-contractual) concerning these terms.</p>
                <h6 className='pt-3 pb-3'>Miscellaneous</h6>
                <p>These Terms and Conditions constitute the entire agreement between Testerika and you concerning the subject matter hereof. In the event that any of the Terms and Conditions are held by a court or other tribunal of competent jurisdiction to be unenforceable, such provisions shall be limited or eliminated to the minimum extent necessary so that these Terms and Conditions shall otherwise remain in full force and effect. A waiver by Testerika or you of any provision of these Terms and Conditions or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof. Testerika may assign its rights or obligations under these Terms and Conditions without condition. These Terms and Conditions will be binding upon and will inure to the benefit of Testerika and you, and Testerika's and your respective successors and permitted assigns.</p>
                <h5 className='fw-bold theme-color mt-3'>Last revised on November 09th, 2024</h5>                 
             </div>
            </div>
        </div>
    </section>
    </>
  )
}

export default TermsConditions